config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :users

  get "/webhook", to: "webhook#verify"
  post "/webhook", to: "webhook#receive_message"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user

  STATUS_OPEN = 1
  STATUS_CLOSED = 2

  def open?
    status == STATUS_OPEN
  end

  def closed?
    status == STATUS_CLOSED
  end

  def response_expired?
    if last_message_sent_at.present?
      Rails.logger.info "Último mensaje enviado en #{last_message_sent_at}, última respuesta: #{last_response_at}"

      expired = (last_response_at.nil? || last_response_at < last_message_sent_at) &&
                last_message_sent_at < 1.hour.ago

      Rails.logger.info "Respuesta expirada: #{expired}"
      expired
    else
      Rails.logger.info "No se ha enviado ningún mensaje aún, last_message_sent_at es nil"
      false
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :store, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy!

    respond_to do |format|
      format.html { redirect_to stores_path, status: :see_other, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.expect(store: [ :name, :rut, :street_name, :ext_number, :int_number, :geolocation, :business_name, :user_id, :email, :status ])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    user = User.find(params[:id])
  
    # Desvincular la tienda antes de eliminar al usuario
    if user.store
      user.store.update(user_id: nil)
    end
  
    user.destroy
    flash[:notice] = "Usuario eliminado correctamente."
    redirect_to users_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :name, :last_name, :rut, :phone, :email ])
    end
end

app/controllers/webhook_controller.rb
class WebhookController < ApplicationController
  skip_before_action :verify_authenticity_token

  # Verificación del Webhook
  def verify
    mode = params["hub.mode"]
    token = params["hub.verify_token"]
    challenge = params["hub.challenge"]

    if mode == "subscribe" && token == ENV["WEBHOOK_VERIFY_TOKEN"]
      render plain: challenge, status: 200
    else
      render plain: "Forbidden", status: 403
    end
  end

  # Recibir mensajes de WhatsApp
  def receive_message
    body = JSON.parse(request.body.read)
    Rails.logger.info "Incoming webhook message: #{body.to_json}"
    
    message = body.dig("entry", 0, "changes", 0, "value", "messages", 0)
    Rails.logger.info "message: #{message}"
    
    if message
      phone_number_id = body.dig("entry", 0, "changes", 0, "value", "metadata", "phone_number_id")
      sender_phone = message["from"]
      
      # Manejar mensaje interactivo (botón presionado)
      if message["type"] == "interactive" && message.dig("interactive", "type") == "button_reply"
        button_id = message.dig("interactive", "button_reply", "id")
        Rails.logger.info "button_id>>: #{button_id}"
        
        user = User.find_by(phone: sender_phone)
  
        if user&.store
          store = user.store
  
          # Determinar el nuevo estado según el botón presionado
          new_status = (button_id == "open_business") ? 1 : 2
          
          # Actualizar el estado de la tienda
          store.update(status: new_status, last_response_at: Time.current)
          # store.update(status: new_status)
  
          Rails.logger.info "Estado de tienda #{store.name} actualizado a #{store.status}"
          
          # Responder al usuario
          send_whatsapp_message(phone_number_id, sender_phone, "Tu tienda ha sido marcada como #{new_status == 2 ? 'Cerrada' : "Abierta"}.", message["id"])
        else
          Rails.logger.warn "No se encontró un usuario con el número #{sender_phone}"
        end
  
        mark_message_as_read(phone_number_id, message["id"])
      end
    end
  
    render json: { status: "ok" }, status: 200
  end

  private

  # Enviar respuesta a WhatsApp
  def send_whatsapp_message(phone_number_id, to, text, message_id)
    uri = URI("https://graph.facebook.com/v18.0/#{phone_number_id}/messages")
    request = Net::HTTP::Post.new(uri, headers)
    request.body = {
      messaging_product: "whatsapp",
      to: to,
      text: { body: "#{text}" },
      context: { message_id: message_id }
    }.to_json

    send_request(uri, request)
  end

  # Marcar mensaje como leído
  def mark_message_as_read(phone_number_id, message_id)
    uri = URI("https://graph.facebook.com/v18.0/#{phone_number_id}/messages")
    request = Net::HTTP::Post.new(uri, headers)
    request.body = {
      messaging_product: "whatsapp",
      status: "read",
      message_id: message_id
    }.to_json

    send_request(uri, request)
  end

  # Encabezados de la API
  def headers
    {
      "Content-Type" => "application/json",
      "Authorization" => "Bearer #{ENV['GRAPH_API_TOKEN']}"
    }
  end

  # Realizar la solicitud HTTP
  def send_request(uri, request)
    response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
      http.request(request)
    end
    Rails.logger.info "API Response: #{response.body}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/webhook_helper.rb
module WebhookHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Localizate" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :rut, style: "display: block" %>
    <%= form.text_field :rut %>
  </div>

  <div>
    <%= form.label :street_name, style: "display: block" %>
    <%= form.text_field :street_name %>
  </div>

  <div>
    <%= form.label :ext_number, style: "display: block" %>
    <%= form.number_field :ext_number %>
  </div>

  <div>
    <%= form.label :int_number, style: "display: block" %>
    <%= form.text_field :int_number %>
  </div>

  <div>
    <%= form.label :geolocation, style: "display: block" %>
    <%= form.text_field :geolocation %>
  </div>

  <div>
    <%= form.label :business_name, style: "display: block" %>
    <%= form.text_field :business_name %>
  </div>

  <div>
    <%= form.label :user_id, "User" %>
    <%= form.collection_select :user_id, User.all, :id, :name, prompt: "Selecciona un usuario" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<div id="<%= dom_id store %>">
  <p>
    <strong>Name:</strong>
    <%= store.name %>
  </p>

  <p>
    <strong>Rut:</strong>
    <%= store.rut %>
  </p>

  <p>
    <strong>Street name:</strong>
    <%= store.street_name %>
  </p>

  <p>
    <strong>Ext number:</strong>
    <%= store.ext_number %>
  </p>

  <p>
    <strong>Int number:</strong>
    <%= store.int_number %>
  </p>

  <p>
    <strong>Geolocation:</strong>
    <%= store.geolocation %>
  </p>

  <p>
    <strong>Business name:</strong>
    <%= store.business_name %>
  </p>

  <p>
    <strong>Admin user:</strong>
    <%= store.user_id %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= store.email %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= store.status %>
  </p>

</div>

app/views/stores/edit.html.erb
<% content_for :title, "Editing store" %>

<h1>Editing store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Show this store", @store %> |
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Stores" %>

<h1>Stores</h1>

<div id="stores">
  <% @stores.each do |store| %>
    <%= render store %>
    <p>
      <%= link_to "Show this store", store %>
    </p>
  <% end %>
</div>

<%= link_to "New store", new_store_path %>

app/views/stores/new.html.erb
<% content_for :title, "New store" %>

<h1>New store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @store %>

<div>
  <%= link_to "Edit this store", edit_store_path(@store) %> |
  <%= link_to "Back to stores", stores_path %>

  <%= button_to "Destroy this store", @store, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :rut, style: "display: block" %>
    <%= form.text_field :rut %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Rut:</strong>
    <%= user.rut %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= user.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>